In [1]:
import pandas as pd

In [3]:
df=pd.read_csv(r'D:\Python-Data-Analysis-Learning\Python\matches.csv')

In [4]:
df

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,11347,2019,Mumbai,05/05/19,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,9,HH Pandya,Wankhede Stadium,Nanda Kishore,O Nandan,S Ravi
752,11412,2019,Chennai,07/05/19,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,bat,normal,0,Mumbai Indians,0,6,AS Yadav,M. A. Chidambaram Stadium,Nigel Llong,Nitin Menon,Ian Gould
753,11413,2019,Visakhapatnam,08/05/19,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,normal,0,Delhi Capitals,0,2,RR Pant,ACA-VDCA Stadium,NaN,NaN,NaN
754,11414,2019,Visakhapatnam,10/05/19,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,6,F du Plessis,ACA-VDCA Stadium,Sundaram Ravi,Bruce Oxenford,Chettithody Shamshuddin
755,11415,2019,Hyderabad,12/05/19,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Mumbai Indians,1,0,JJ Bumrah,Rajiv Gandhi Intl. Cricket Stadium,Nitin Menon,Ian Gould,Nigel Llong

In [ ]:
print(df.to_string()) #use to_string() to print the entire DataFrame.

        id  season            city        date                        team1                        team2                  toss_winner toss_decision     result  dl_applied                       winner  win_by_runs  win_by_wickets    player_of_match                                                 venue                umpire1                umpire2                  umpire3
0        1    2017       Hyderabad  2017-04-05          Sunrisers Hyderabad  Royal Challengers Bangalore  Royal Challengers Bangalore         field     normal           0          Sunrisers Hyderabad           35               0       Yuvraj Singh             Rajiv Gandhi International Stadium, Uppal            AY Dandekar               NJ Llong                      NaN
1        2    2017            Pune  2017-04-06               Mumbai Indians       Rising Pune Supergiant       Rising Pune Supergiant         field     normal           0       Rising Pune Supergiant            0               7          SPD Smith               Maharashtra Cricket Association Stadium         A Nand Kishore                 S Ravi                      NaN
2        3    2017          Rajkot  2017-04-07                Gujarat Lions        Kolkata Knight Riders        Kolkata Knight Riders         field     normal           0        Kolkata Knight Riders            0              10            CA Lynn                Saurashtra Cricket Association Stadium            Nitin Menon              CK Nandan                      NaN
3        4    2017          Indore  2017-04-08       Rising Pune Supergiant              Kings XI Punjab              Kings XI Punjab         field     normal           0              Kings XI Punjab            0               6         GJ Maxwell                                Holkar Cricket Stadium           AK Chaudhary          C Shamshuddin                      NaN
4        5    2017       Bangalore  2017-04-08  Royal Challengers Bangalore             Delhi Daredevils  Royal Challengers Bangalore           bat     normal           0  Royal Challengers Bangalore           15               0          KM Jadhav                                 M Chinnaswamy Stadium                    NaN                    NaN                      NaN
5        6    2017       Hyderabad  2017-04-09                Gujarat Lions          Sunrisers Hyderabad          Sunrisers Hyderabad         field     normal           0          Sunrisers Hyderabad            0               9        Rashid Khan             Rajiv Gandhi International Stadium, Uppal             A Deshmukh               NJ Llong                      NaN
6        7    2017          Mumbai  2017-04-09        Kolkata Knight Riders               Mumbai Indians               Mumbai Indians         field     normal           0               Mumbai Indians            0               4             N Rana                                      Wankhede Stadium            Nitin Menon              CK Nandan                      NaN
7        8    2017          Indore  2017-04-10  Royal Challengers Bangalore              Kings XI Punjab  Royal Challengers Bangalore           bat     normal           0              Kings XI Punjab            0               8           AR Patel                                Holkar Cricket Stadium           AK Chaudhary          C Shamshuddin                      NaN
8        9    2017            Pune  2017-04-11             Delhi Daredevils       Rising Pune Supergiant       Rising Pune Supergiant         field     normal           0             Delhi Daredevils           97               0          SV Samson               Maharashtra Cricket Association Stadium            AY Dandekar                 S Ravi                      NaN
9       10    2017          Mumbai  2017-04-12          Sunrisers Hyderabad               Mumbai Indians               Mumbai Indians         field     normal           0               Mumbai Indians            0               4          JJ Bumrah                                      Wankhede Stadium            Nitin Menon              CK Nandan                      NaN
10      11    2017         Kolkata  2017-04-13              Kings XI Punjab        Kolkata Knight Riders        Kolkata Knight Riders         field     normal           0        Kolkata Knight Riders            0               8          SP Narine                                          Eden Gardens             A Deshmukh               NJ Llong                      NaN
11      12    2017       Bangalore  2017-04-14  Royal Challengers Bangalore               Mumbai Indians               Mumbai Indians         field     normal           0               Mumbai Indians            0               4         KA Pollard                                 M Chinnaswamy Stadium  KN Ananthapadmanabhan           AK Chaudhary                      NaN
12      13    2017          Rajkot  2017-04-14       Rising Pune Supergiant                Gujarat Lions                Gujarat Lions         field     normal           0                Gujarat Lions            0               7             AJ Tye                Saurashtra Cricket Association Stadium         A Nand Kishore                 S Ravi                      NaN
13      14    2017         Kolkata  2017-04-15        Kolkata Knight Riders          Sunrisers Hyderabad          Sunrisers Hyderabad         field     normal           0        Kolkata Knight Riders           17               0         RV Uthappa                                          Eden Gardens            AY Dandekar               NJ Llong                      NaN
14      15    2017           Delhi  2017-04-15             Delhi Daredevils              Kings XI Punjab             Delhi Daredevils           bat     normal           0             Delhi Daredevils           51               0        CJ Anderson                                      Feroz Shah Kotla               YC Barde            Nitin Menon                      NaN
15      16    2017          Mumbai  2017-04-16                Gujarat Lions               Mumbai Indians               Mumbai Indians         field     normal           0               Mumbai Indians            0               6             N Rana                                      Wankhede Stadium         A Nand Kishore                 S Ravi                      NaN
16      17    2017       Bangalore  2017-04-16       Rising Pune Supergiant  Royal Challengers Bangalore  Royal Challengers Bangalore         field     normal           0       Rising Pune Supergiant           27               0          BA Stokes                                 M Chinnaswamy Stadium  KN Ananthapadmanabhan          C Shamshuddin                      NaN
17      18    2017           Delhi  2017-04-17             Delhi Daredevils        Kolkata Knight Riders             Delhi Daredevils           bat     normal           0        Kolkata Knight Riders            0               4    NM Coulter-Nile                                      Feroz Shah Kotla            Nitin Menon              CK Nandan                      NaN
18      19    2017       Hyderabad  2017-04-17          Sunrisers Hyderabad              Kings XI Punjab              Kings XI Punjab         field     normal           0          Sunrisers Hyderabad            5               0            B Kumar             Rajiv Gandhi International Stadium, Uppal            AY Dandekar             A Deshmukh                      NaN
19      20    2017          Rajkot  2017-04-18  Royal Challengers Bangalore                Gujarat Lions                Gujarat Lions         field     normal           0  Royal Challengers Bangalore           21               0           CH Gayle                Saurashtra Cricket Association Stadium                 S Ravi              VK Sharma                      NaN
20      21    2017       Hyderabad  2017-04-19          Sunrisers Hyderabad             Delhi Daredevils          Sunrisers Hyderabad           bat     normal           0          Sunrisers Hyderabad           15               0      KS Williamson             Rajiv Gandhi International Stadium, Uppal            CB Gaffaney               NJ Llong                      NaN
21      22    2017          Indore  2017-04-20              Kings XI Punjab               Mumbai Indians               Mumbai Indians         field     normal           0               Mumbai Indians            0               8         JC Buttler                                Holkar Cricket Stadium              M Erasmus          C Shamshuddin                      NaN
22      23    2017         Kolkata  2017-04-21        Kolkata Knight Riders                Gujarat Lions                Gujarat Lions         field     normal           0                Gujarat Lions            0               4           SK Raina                                          Eden Gardens            CB Gaffaney            Nitin Menon                      NaN
23      24    2017          Mumbai  2017-04-22               Mumbai Indians             Delhi Daredevils             Delhi Daredevils         field     normal           0               Mumbai Indians           14               0     MJ McClenaghan                                      Wankhede Stadium         A Nand Kishore                 S Ravi                      NaN
24      25    2017            Pune  2017-04-22          Sunrisers Hyderabad       Rising Pune Supergiant       Rising Pune Supergiant         field     normal           0       Rising Pune Supergiant            0               6           MS Dhoni               Maharashtra Cricket Association Stadium            AY Dandekar             A Deshmukh                      NaN
25      26    2017          Rajkot  2017-04-23              Kings XI Punjab                Gujarat Lions                Gujarat Lions         field     normal           0              Kings XI Punjab           26               0            HM Amla                Saurashtra Cricket Association Stadium           AK Chaudhary              M Erasmus                      NaN
26      27    2017         Kolkata  2017-04-23        Kolkata Knight Riders  Royal Challengers Bangalore  Royal Challengers Bangalore         field     normal           0        Kolkata Knight Riders           82               0    NM Coulter-Nile                                          Eden Gardens            CB Gaffaney              CK Nandan                      NaN
27      28    2017          Mumbai  2017-04-24       Rising Pune Supergiant               Mumbai Indians               Mumbai Indians         field     normal           0       Rising Pune Supergiant            3               0          BA Stokes                                      Wankhede Stadium         A Nand Kishore                 S Ravi                      NaN
28      29    2017            Pune  2017-04-26       Rising Pune Supergiant        Kolkata Knight Riders        Kolkata Knight Riders         field     normal           0        Kolkata Knight Riders            0               7         RV Uthappa               Maharashtra Cricket Association Stadium            AY Dandekar               NJ Llong                      NaN
29      30    2017       Bangalore  2017-04-27  Royal Challengers Bangalore                Gujarat Lions                Gujarat Lions         field     normal           0                Gujarat Lions            0               7             AJ Tye                                 M Chinnaswamy Stadium           AK Chaudhary          C Shamshuddin                      NaN
30      31    2017         Kolkata  2017-04-28             Delhi Daredevils        Kolkata Knight Riders        Kolkata Knight Riders         field     normal           0        Kolkata Knight Riders            0               7          G Gambhir                                          Eden Gardens               NJ Llong                 S Ravi                      NaN
31      32    2017      Chandigarh  2017-04-28          Sunrisers Hyderabad              Kings XI Punjab              Kings XI Punjab         field     normal           0          Sunrisers Hyderabad           26               0        Rashid Khan  Punjab Cricket Association IS Bindra Stadium, Mohali            Nitin Menon              CK Nandan                      NaN
32      33    2017            Pune  2017-04-29       Rising Pune Supergiant  Royal Challengers Bangalore  Royal Challengers Bangalore         field     normal           0       Rising Pune Supergiant           61               0        LH Ferguson               Maharashtra Cricket Association Stadium  KN Ananthapadmanabhan              M Erasmus                      NaN
33      34    2017          Rajkot  2017-04-29                Gujarat Lions               Mumbai Indians                Gujarat Lions           bat        tie           0               Mumbai Indians            0               0          KH Pandya                Saurashtra Cricket Association Stadium           AK Chaudhary            CB Gaffaney                      NaN
34      35    2017      Chandigarh  2017-04-30             Delhi Daredevils              Kings XI Punjab              Kings XI Punjab         field     normal           0              Kings XI Punjab            0              10     Sandeep Sharma  Punjab Cricket Association IS Bindra Stadium, Mohali               YC Barde              CK Nandan                      NaN
35      36    2017       Hyderabad  2017-04-30          Sunrisers Hyderabad        Kolkata Knight Riders        Kolkata Knight Riders         field     normal           0          Sunrisers Hyderabad           48               0          DA Warner             Rajiv Gandhi International Stadium, Uppal            AY Dandekar                 S Ravi                      NaN
36      37    2017          Mumbai  2017-05-01  Royal Challengers Bangalore               Mumbai Indians  Royal Challengers Bangalore           bat     normal           0               Mumbai Indians            0               5          RG Sharma                                      Wankhede Stadium           AK Chaudhary            CB Gaffaney                      NaN
37      38    2017            Pune  2017-05-01                Gujarat Lions       Rising Pune Supergiant       Rising Pune Supergiant         field     normal           0       Rising Pune Supergiant            0               5          BA Stokes               Maharashtra Cricket Association Stadium              M Erasmus          C Shamshuddin                      NaN
38      39    2017           Delhi  2017-05-02          Sunrisers Hyderabad             Delhi Daredevils             Delhi Daredevils         field     normal           0             Delhi Daredevils            0               6     Mohammed Shami                                      Feroz Shah Kotla               YC Barde            Nitin Menon                      NaN
39      40    2017         Kolkata  2017-05-03        Kolkata Knight Riders       Rising Pune Supergiant       Rising Pune Supergiant         field     normal           0       Rising Pune Supergiant            0               4        RA Tripathi                                          Eden Gardens  KN Ananthapadmanabhan         A Nand Kishore                      NaN
40      41    2017           Delhi  2017-05-04                Gujarat Lions             Delhi Daredevils             Delhi Daredevils         field     normal           0             Delhi Daredevils            0               7            RR Pant                                      Feroz Shah Kotla              M Erasmus            Nitin Menon                      NaN
41      42    2017       Bangalore  2017-05-05              Kings XI Punjab  Royal Challengers Bangalore  Royal Challengers Bangalore         field     normal           0              Kings XI Punjab           19               0     Sandeep Sharma                                 M Chinnaswamy Stadium            CB Gaffaney          C Shamshuddin                      NaN
42      43    2017       Hyderabad  2017-05-06       Rising Pune Supergiant          Sunrisers Hyderabad          Sunrisers Hyderabad         field     normal           0       Rising Pune Supergiant           12               0         JD Unadkat             Rajiv Gandhi International Stadium, Uppal  KN Ananthapadmanabhan           AK Chaudhary                      NaN
43      44    2017           Delhi  2017-05-06               Mumbai Indians             Delhi Daredevils             Delhi Daredevils         field     normal           0               Mumbai Indians          146               0        LMP Simmons                                      Feroz Shah Kotla            Nitin Menon              CK Nandan                      NaN
44      45    2017       Bangalore  2017-05-07  Royal Challengers Bangalore        Kolkata Knight Riders        Kolkata Knight Riders         field     normal           0        Kolkata Knight Riders            0               6          SP Narine                                 M Chinnaswamy Stadium            AY Dandekar          C Shamshuddin                      NaN
45      46    2017      Chandigarh  2017-05-07              Kings XI Punjab                Gujarat Lions                Gujarat Lions         field     normal           0                Gujarat Lions            0               6           DR Smith  Punjab Cricket Association IS Bindra Stadium, Mohali         A Nand Kishore              VK Sharma                      NaN
46      47    2017       Hyderabad  2017-05-08               Mumbai Indians          Sunrisers Hyderabad               Mumbai Indians           bat     normal           0          Sunrisers Hyderabad            0               7           S Dhawan             Rajiv Gandhi International Stadium, Uppal  KN Ananthapadmanabhan              M Erasmus                      NaN
47      48    2017      Chandigarh  2017-05-09              Kings XI Punjab        Kolkata Knight Riders        Kolkata Knight Riders         field     normal           0              Kings XI Punjab           14               0          MM Sharma  Punjab Cricket Association IS Bindra Stadium, Mohali         A Nand Kishore                 S Ravi                      NaN
48      49    2017          Kanpur  2017-05-10                Gujarat Lions             Delhi Daredevils             Delhi Daredevils         field     normal           0             Delhi Daredevils            0               2            SS Iyer                                            Green Park               YC Barde           AK Chaudhary                      NaN
49      50    2017          Mumbai  2017-05-11              Kings XI Punjab               Mumbai Indians               Mumbai Indians         field     normal           0              Kings XI Punjab            7               0            WP Saha                                      Wankhede Stadium             A Deshmukh         A Nand Kishore                      NaN
50      51    2017           Delhi  2017-05-12             Delhi Daredevils       Rising Pune Supergiant             Delhi Daredevils           bat     normal           0             Delhi Daredevils            7               0            KK Nair                                      Feroz Shah Kotla  KN Ananthapadmanabhan              CK Nandan                      NaN
51      52    2017          Kanpur  2017-05-13                Gujarat Lions          Sunrisers Hyderabad          Sunrisers Hyderabad         field     normal           0          Sunrisers Hyderabad            0               8     Mohammed Siraj                                            Green Park           AK Chaudhary            Nitin Menon                      NaN

In [10]:
pd.options.display.max_rows

60

In [11]:
pd.options.display.max_rows=200

In [12]:
df

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,11347,2019,Mumbai,05/05/19,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,9,HH Pandya,Wankhede Stadium,Nanda Kishore,O Nandan,S Ravi
752,11412,2019,Chennai,07/05/19,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,bat,normal,0,Mumbai Indians,0,6,AS Yadav,M. A. Chidambaram Stadium,Nigel Llong,Nitin Menon,Ian Gould
753,11413,2019,Visakhapatnam,08/05/19,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,normal,0,Delhi Capitals,0,2,RR Pant,ACA-VDCA Stadium,NaN,NaN,NaN
754,11414,2019,Visakhapatnam,10/05/19,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,6,F du Plessis,ACA-VDCA Stadium,Sundaram Ravi,Bruce Oxenford,Chettithody Shamshuddin
755,11415,2019,Hyderabad,12/05/19,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Mumbai Indians,1,0,JJ Bumrah,Rajiv Gandhi Intl. Cricket Stadium,Nitin Menon,Ian Gould,Nigel Llong