# Session 2: Exploratory Data Analysis & Basic Statistics

### Learning Objectives
- Understand the importance of Exploratory Data Analysis (EDA).
- Explore and summarize datasets using Pandas.
- Identify missing values and duplicate records.
- Understand descriptive statistics.
- Calculate Mean, Median, and Mode.
- Compare different measures of central tendency.
- Interpret statistical results.
- Apply these concepts using Python.

### Topics Covered
- Introduction to Exploratory Data Analysis (EDA)
- Measures of Central Tendency (Mean, Median, Mode)
- Measures of Dispersion (Range, Variance, Standard Deviation, IQR)
- Missing Value Imputation using Constants
- Mean Imputation
- Median Imputation
- Mode Imputation

# What is Exploratory Data Analysis (EDA)?

Exploratory Data Analysis (EDA) is the process of examining, cleaning, summarizing, and visualizing data before building Machine Learning models.

EDA helps us understand:
- Structure of the dataset
- Data types
- Missing values
- Duplicate records
- Outliers
- Feature distributions
- Relationships among variables

EDA is often called the first and most important step in Data Analysis and Machine Learning.

### Why is EDA Important?

Imagine receiving marks of 5,000 students without any explanation.

Questions that immediately arise are:

- How many students are there?
- Are there missing values?
- What is the average score?
- Are there any incorrect entries?
- Are there duplicate records?
- Is the data balanced?

EDA answers these questions before model building.

### EDA Workflow

A typical EDA process includes:

1. Load the dataset
2. Inspect the data
3. Understand data types
4. Check missing values
5. Remove duplicates
6. Generate descriptive statistics
7. Visualize distributions
8. Detect outliers
9. Study feature relationships

In [1]:
# Import common libraries


import pandas as pd
import numpy as np

## 1. Loading the Dataset

The Titanic dataset is one of the most popular and widely used datasets for learning Data Analysis, Data Preprocessing, and Machine Learning. It contains information about the passengers who were aboard the RMS Titanic, which sank on 15 April 1912 after colliding with an iceberg during its maiden voyage from Southampton to New York.

Each row represents a passenger on the Titanic. The dataset includes demographic details such as a passenger's age, gender, ticket class, fare, number of siblings or spouses aboard, number of parents or children aboard, port of embarkation, and whether the passenger survived the disaster.

Some important columns include:

| Column   | Description                          |
| -------- | ------------------------------------ |
| survived | Whether the passenger survived (0/1) |
| pclass   | Passenger Class                      |
| sex      | Gender                               |
| age      | Passenger Age                        |
| fare     | Ticket Fare                          |
| embarked | Port of Embarkation                  |
| class    | Travel Class                         |
| who      | Man/Woman/Child                      |
| alive    | Yes/No                               |

In [2]:
df=pd.read_csv(r"D:\Python-Data-Analysis-Learning\EDA\Univariate_EDA\train.csv")

## 2. Inspect the Data

### Display First Five Rows

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### Display Last Five Rows

In [4]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

### Shape of Dataset

In [5]:
df.shape

(891, 12)

### Column Names

In [6]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

## 3. Understand Data Types

In [7]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

### Dataset Information

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

#### Descriptive Statistics

In [9]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [10]:
# Describe Categorical Features
df.describe(include="object")

                       Name   Sex  Ticket Cabin Embarked
count                   891   891     891   204      889
unique                  891     2     681   147        3
top     Dooley, Mr. Patrick  male  347082    G6        S
freq                      1   577       7     4      644

## 4. Check Missing Values

Real-world datasets often contain missing values.

Let's identify them.

#### Count Missing Values

#### Percentage of Missing Values

#### Try Yourself


1. Find number of missing values in Age.
2. Find number of missing values in Deck.
3. Percentage of missing values in Deck.

Which feature would you consider dropping?

1. Find number of missing values in Age.

2. Find number of missing values in Deck.

We'll explore what to do with missing values in few minutes.

## 5. Remove Duplicates

In [11]:
# Verify

## 6. Generate Descriptive Statistic

### 6.1 Exploring Numerical Features

### Exploring Categorical Features

### 6.2 Distribution of Age

### Distribution of Fare

#### Try Yourself
Create the following plots
1. Box Plot of Fare.
2. Count Plot of Passenger Class. Also report the Survival Count.
4. Count Plot of Embarked

### 6.3 Correlation Analysis

### Correlation Heatmap

### 6.4 Measures of Central Tendency

Central tendency refers to the center of a dataset.

The three common measures are:
1. Mean
2. Median
3. Mode

#### Mean

The Mean is the arithmetic average of all observations.

Formula: $$\text{Mean} = \frac{\Sigma x}{n}$$

In [12]:
# What is the average age of passengers?

#### Try Yourself

Calculate the Mean of:
- Fare
- Age
- SibSp
- Parch

Which numerical feature has the highest average?

#### Median

Median is the middle value after sorting. Unlike Mean, it is less affected by outliers.

Formula:
- Case 1: Odd Number of Observations
$$
\text{Median} = x_{\frac{n+1}{2}}
$$
- Case 2: Even Number of Observations
$$
\text{Median} =
\frac{x_{\frac{n}{2}} + x_{\frac{n}{2}+1}}{2}
$$

#### Mode

Mode is the most frequently occurring value. Unlike Mean and Median, Mode can also be used for categorical variables.

In [13]:
df['Age'].mode()

0    24.0
Name: Age, dtype: float64

#### Try Yourself
1. Which gender appears most frequently?
2. From where most passengers embarked?
3. Most passengers were of which class?
4. Were there more men than women on the ship?

### 6.5 Measures of Dispersion

**What is Dispersion?** Measures of Dispersion describe how spread out the data values are from the center.

Two datasets may have the same mean but completely different spreads.

Example:
- Dataset A = [48, 49, 50, 51, 52]
- Dataset B = [10, 30, 50, 70, 90]

Both datasets have: `Mean = 50`. But Dataset B has much greater variation. Dispersion helps quantify this variation.

---

#### Types of Dispersion

We commonly use:
1. Range
2. Variance
3. Standard Deviation
4. Interquartile Range (IQR)

#### 1. Range

Range is the difference between the maximum and minimum values.

Formula: $$\text{Range} = Maximum − Minimum$$

In [14]:
# Range of Passenger Age
age_range=df['Age'].max()-df['Age'].min()
age_range

np.float64(79.58)

In [15]:
# Range of Fare
fare_range=df['Fare'].max()-df['Fare'].min()
fare_range

np.float64(512.3292)

#### Try Yourself

Calculate the Range for:
- Age
- SibSp
- Parch

Which feature has the largest range?

#### 2. Variance

Variance measures how far observations are from the mean. Larger variance indicates greater spread.

In [16]:
# Variance of Age

In [17]:
# Variance of Fare

#### 3. Standard Deviation

Standard Deviation is the square root of Variance. It represents the average distance of data points from the mean.

In [18]:
# Standard Deviation of Age
df['Age'].std()

np.float64(14.526497332334042)

In [19]:
# Standard Deviation of Fare
df['Fare'].std()

np.float64(49.6934285971809)

#### 4. Interquartile Range (IQR)

A *percentile* is a statistical measure which tells us how a value compares with the rest of the data. For example, if a student's score is in the 80th percentile, it means the student scored higher than or equal to 80% of the students, while only 20% scored higher than her/him.

| Percentile       | Meaning                                 |
| ---------------- | --------------------------------------- |
| 0th              | Minimum value                           |
| 25th (Q1)        | 25% of values lie below this point      |
| 50th (Median/Q2) | Half of the values lie below this point |
| 75th (Q3)        | 75% of values lie below this point      |
| 100th            | Maximum value                           |

IQR measures the spread of the middle 50% of observations. It is less affected by outliers.

Formula: `IQR = Q3 − Q1`

Where,
- Q1 = 25th Percentile
- Q3 = 75th Percentile

In [20]:
# Calculate IQR of Age\

In [21]:
# Box Plot

#### Try Yourself

Calculate the IQR for:
- Fare

Draw boxplots for both columns.

Which feature contains more outliers - Age or Fare?

# Introduction to Missing Values

**What are Missing Values?** Missing values occur when information is unavailable.

Examples:
- Passenger Age not recorded.
- Embarked location missing.
- Deck information unavailable.

Missing values appear as: `NaN`

#### Why Handle Missing Values?

Machine Learning algorithms cannot work properly with missing data.

Missing values may:
- Reduce model accuracy.
- Cause training errors.
- Introduce bias.

### Method 1: Constant Value Imputation

Replace missing values with a fixed value.

In [22]:
# Replace Age with 0
df_const=df.copy()
df_const['Age']=df_const['Age'].fillna(0)
df_const['Age'].isnull().sum()

np.int64(0)

In [30]:
# Replace Embarked with "Unknown"
df_const['Embarked']=df_const["Embarked"].fillna("Unknown")

### When to Use?

Useful when:
- Missing itself carries meaning.
- A default category is acceptable.

#### Try Yourself

Fill missing values in:
- Age using $-1$
- Embarked using "Missing"

Check whether missing values remain.

### Method 2: Mean Imputation

Suitable for normally distributed numerical data.

In [34]:
# Mean of Age
mean_age=df['Age'].mean()
mean_age

np.float64(29.69911764705882)

In [ ]:
# Fill Missing Age
df['Age'].fillna(df['Age'].mean())

np.int64(0)

#### Advantages
- Simple
- Preserves sample size

#### Limitations
- Affected by outliers.

#### Try Yourself

- Replace missing Fare values using the Mean.
- Compare the average Fare before and after imputation.

### Method 3: Median Imputation

Median works better for skewed distributions.

In [35]:
# Fill Missing Age
df['Age'].fillna(df['Age'].median())

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888    28.0
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

#### Why Median?

Age and Fare often contain outliers. Median is less affected by extreme values.

#### Try Yourself

Replace missing Age values using the Median.

Compare:
- Mean Imputation
- Median Imputation

Which seems more appropriate?

### Method 4: Mode Imputation

Mode is commonly used for categorical features.

In [28]:
# Find Mode

In [29]:
# Mode Imputation for Sex

#### Try Yourself

Apply Mode Imputation to:
- Embarked
- Embark Town
- Deck

Which columns are suitable for Mode Imputation?

### Comparison of Imputation Methods

| Method   | Best For                            | Affected by Outliers? |
| -------- | ----------------------------------- | --------------------- |
| Constant | Default values                      | No                    |
| Mean     | Normally distributed numerical data | Yes                   |
| Median   | Skewed numerical data               | No                    |
| Mode     | Categorical data                    | No                    |

<img src="attachment:be9a16bd-eec8-4060-92a2-34fb0d6a5508.png" width="70%"/>